# coding: utf-8

"""
    CoderBot Cloud API - Robot only - OpenAPI 3.0

    CoderBot Cloud API - Robot only  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: info@coderbot.org
    Generated by: https://openapi-generator.tech
"""

from cloud_api_robot_client.paths.robot_activities.post import CreateRobotActivity
from cloud_api_robot_client.paths.robot_programs.post import CreateRobotProgram
from cloud_api_robot_client.paths.robot_activities_activity_id.delete import DeleteRobotActivity
from cloud_api_robot_client.paths.robot_programs_program_id.delete import DeleteRobotProgram
from cloud_api_robot_client.paths.robot_activities.get import GetRobotActivities
from cloud_api_robot_client.paths.robot_data.get import GetRobotData
from cloud_api_robot_client.paths.robot_programs.get import GetRobotPrograms
from cloud_api_robot_client.paths.robot_setting.get import GetRobotSetting
from cloud_api_robot_client.paths.robot_register.post import RegisterRobot
from cloud_api_robot_client.paths.robot_activities_activity_id.put import SetRobotActivity
from cloud_api_robot_client.paths.robot_programs_program_id.put import SetRobotProgram
from cloud_api_robot_client.paths.robot_setting.put import SetRobotSetting
from cloud_api_robot_client.paths.robot_data.put import UpdateRobotData


class RobotSyncApi(
    CreateRobotActivity,
    CreateRobotProgram,
    DeleteRobotActivity,
    DeleteRobotProgram,
    GetRobotActivities,
    GetRobotData,
    GetRobotPrograms,
    GetRobotSetting,
    RegisterRobot,
    SetRobotActivity,
    SetRobotProgram,
    SetRobotSetting,
    UpdateRobotData,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
