# coding: utf-8

"""
    CoderBot Cloud API - Robot only - OpenAPI 3.0

    CoderBot Cloud API - Robot only  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: info@coderbot.org
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "cloud-api-robot-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="CoderBot Cloud API - Robot only - OpenAPI 3.0",
    author="OpenAPI Generator community",
    author_email="info@coderbot.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "CoderBot Cloud API - Robot only - OpenAPI 3.0"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    CoderBot Cloud API - Robot only  # noqa: E501
    """
)
