# coding: utf-8

"""
    CoderBot Cloud API - Robot only - OpenAPI 3.0

    CoderBot Cloud API - Robot only  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: info@coderbot.org
    Generated by: https://openapi-generator.tech
"""

import unittest

import cloud_api_robot_client
from cloud_api_robot_client.model.robot_credentials import RobotCredentials
from cloud_api_robot_client import configuration


class TestRobotCredentials(unittest.TestCase):
    """RobotCredentials unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
